ALTER TABLE landings DROP COLUMN IF EXISTS notes;

ALTER TABLE offers DROP COLUMN IF EXISTS daily_cap;
ALTER TABLE offers DROP COLUMN IF EXISTS notes;

ALTER TABLE campaigns DROP COLUMN IF EXISTS tags;
ALTER TABLE campaigns DROP COLUMN IF EXISTS notes;
ALTER TABLE campaigns DROP COLUMN IF EXISTS cost_value;
ALTER TABLE campaigns DROP COLUMN IF EXISTS cost_model;
ALTER TABLE campaigns DROP COLUMN IF EXISTS group_id;

DROP TYPE IF EXISTS cost_model;
DROP TABLE IF EXISTS campaign_groups;
